web:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - .:/app
  working_dir: /app
  command: bundle exec shotgun --port=3000 -o 0.0.0.0
  links:
    - db
db:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: app_development
